# Generated by Django 4.1.1 on 2022-09-27 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jeniskamar',
            fields=[
                ('ID_jenisKamar', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('HargaKamar', models.IntegerField()),
                ('DeskripsiKamar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='kamar',
            fields=[
                ('ID_kamar', models.AutoField(primary_key=True, serialize=False)),
                ('statuskamar', models.BooleanField(default=False)),
                ('nokamar', models.IntegerField(null=True)),
                ('jeniskamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jeniskamar')),
            ],
        ),
        migrations.CreateModel(
            name='pelanggan',
            fields=[
                ('ID_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jeniskelamin', models.CharField(max_length=10)),
                ('tanggallahir', models.DateField()),
                ('nohp', models.IntegerField()),
                ('emailplg', models.EmailField(max_length=254)),
                ('alamat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='resepsionis',
            fields=[
                ('ID_resepsionis', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jeniskelamin', models.CharField(max_length=10)),
                ('nohp', models.IntegerField()),
                ('katasandi', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='pemesanan',
            fields=[
                ('KodeBooking', models.AutoField(primary_key=True, serialize=False)),
                ('CheckIn', models.DateField()),
                ('CheckOut', models.DateField()),
                ('LamaMenginap', models.IntegerField(null=True)),
                ('ID_Kamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kamar')),
                ('ID_Pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pelanggan')),
                ('ID_Resepsionis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resepsionis')),
            ],
        ),
        migrations.CreateModel(
            name='pembayaran',
            fields=[
                ('ID_Pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('MetodePembayaran', models.CharField(max_length=10)),
                ('TanggalPembayaran', models.DateField()),
                ('KodeBooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pemesanan')),
            ],
        ),
    ]
