# Generated by Django 4.1.1 on 2022-09-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pemesanan',
            old_name='ID_Kamar',
            new_name='ID_kamar',
        ),
        migrations.RenameField(
            model_name='pemesanan',
            old_name='ID_Pelanggan',
            new_name='ID_pelanggan',
        ),
        migrations.RenameField(
            model_name='pemesanan',
            old_name='ID_Resepsionis',
            new_name='ID_resepsionis',
        ),
    ]
